container:
  image: ruby:latest

test_task:
  bundle_cache:
    folder: /usr/local/bundle
    fingerprint_script: cat Gemfile.lock
    populate_script: bundle install
  test_script: bundle exec rails test:system
