os: linux
sudo: required
dist: trusty
env: DISPLAY=':99.0'

language: ruby

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - chromium-chromedriver

before_script:
  - wget http://chromedriver.storage.googleapis.com/2.36/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - sudo cp chromedriver /usr/local/bin/
  - sudo chmod +x /usr/local/bin/chromedriver
  - sh -e /etc/init.d/xvfb start
  - sleep 3

script:
  - bundle exec rails db:create test:system
