sudo: required

language: ruby

services:
  - docker

install: true # skip the installation step entirely

script:
  - docker-compose -f docker-compose.test.yml pull
  - bin/rails docker:build
  - bin/rails docker:test
