version: '3.4'
services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD
    volumes:
      - db-data:/var/lib/postgresql/data

  selenium:
    image: selenium/standalone-chrome
    ports:
      - 4444:4444
      - 5900:5900

  app:
    build:
      context: .
      args:
        - ADDITIONAL_PACKAGES=nodejs-current chromium chromium-chromedriver
        - EXECJS_RUNTIME=Node
        - BUNDLE_WITHOUT=production
        - RAILS_ENV=test
    environment:
      RAILS_ENV: test
      DB_HOST: db
      POSTGRES_PASSWORD: catapimba
      SECRET_KEY_BASE: we-dont-need-a-secret-here
      SELENIUM_REMOTE_HOST: selenium
      DB_USER: postgres
      DB_PASSWORD: catapimba
      APP_ADMIN_EMAIL: admin@example.org
      APP_ADMIN_PASSWORD: secret
      APP_EMAIL: reply@example.org
      APP_HOST: example.org
    ports:
      - 3000
    links:
      - db
      - selenium

volumes:
  db-data:
